keychain:
  backend-1.mycompany.example:
    algorithm: RS256
    value: 'LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEzWEViYURqTUlRekdiYlBlU1hwTAp2ZVRYdGFLTlhrVmRYR2szbjdsREdxQWZBRW1SZWE5ZzR5SENTUUhPMTRVdUhXY0NtcDdwU3VQbDdjeXZ0aW5aCmFiMWRpRVBLc1YrNEF2VGVFVy9sWDZBNnRqNmRpQWpDQUVMUDk4ZStNTTg3NzJ3RjdSRytiSGtqaGJORFBCZ2gKNjJ1V3lEeVlLT3Y1RlpGOWdTZmx4UG5Nb3ZWOFdvckhDTHZuckVvSjA2MzZJYjdpeU9OMHlwZmhuWVNEd3BCNQpSc0tXSHpsM3dKRUtmcXZsY2g1eUkxcnB2c0Nzbkg0ckowNDF3MXBPcHhyT3ZFSEI3bVFwakV3bm10YldlcnNZCjREbTQ4Q3lNWFQwcDBWWFFnSDcxR1hVc3UvVEU0OXlxbldVaDJUSTV6cnIyOXdkcCtBUmJYNGd6dmJZUEdra1UKWVFJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
'
  backend-2.mycompany.example:
    algorithm: RS256
    value: 'LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUEzWEViYURqTUlRekdiYlBlU1hwTAp2ZVRYdGFLTlhrVmRYR2szbjdsREdxQWZBRW1SZWE5ZzR5SENTUUhPMTRVdUhXY0NtcDdwU3VQbDdjeXZ0aW5aCmFiMWRpRVBLc1YrNEF2VGVFVy9sWDZBNnRqNmRpQWpDQUVMUDk4ZStNTTg3NzJ3RjdSRytiSGtqaGJORFBCZ2gKNjJ1V3lEeVlLT3Y1RlpGOWdTZmx4UG5Nb3ZWOFdvckhDTHZuckVvSjA2MzZJYjdpeU9OMHlwZmhuWVNEd3BCNQpSc0tXSHpsM3dKRUtmcXZsY2g1eUkxcnB2c0Nzbkg0ckowNDF3MXBPcHhyT3ZFSEI3bVFwakV3bm10YldlcnNZCjREbTQ4Q3lNWFQwcDBWWFFnSDcxR1hVc3UvVEU0OXlxbldVaDJUSTV6cnIyOXdkcCtBUmJYNGd6dmJZUEdra1UKWVFJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
'


jwt:
  verify_jti: true
  verify_aud: true
  exp_leeway: 180
